[tool.poetry]
name = "gotrue"
version = "2.0.0"
description = "Python Client Library for GoTrue"
authors = ["Joel Lee <joel@joellee.org>", "Leon Fedden <leonfedden@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
requests = "^2.25"
sphinx = "*"
recommonmark = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
