[tool.poetry]
name = "gotrue"
version = "0.2.0"
description = "Python Client Library for GoTrue"
authors = ["Joel Lee <joel@joellee.org>"]
homepage = "https://github.com/supabase-community/gotrue-py"
repository = "https://github.com/supabase-community/gotrue-py"
documentation = "https://github.com/supabase-community/gotrue-py"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
Sphinx = "^4.2.0"
flake8 = "^3.9.2"
black = "^21.9b0"
isort = "^5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
